version: "3.3"

services:
  app:
    build: ../
    container_name: app
    volumes:
      - "../config.yaml:/app/config.yaml"
    ports:
      - "8080:8080"
    networks:
      - app

networks:
  app:
    driver: bridge
